version: '3'
services:
  app:
    image: webdevops/php-apache:7.4-alpine
    volumes:
      - ${PWD}/:/app
      - ${PWD}/docker/httpd/vhost.conf:/opt/docker/etc/httpd/vhost.conf
    ports:
      - "80:80"

  database:
    image: library/mysql:latest
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ${PWD}/docker/mysql/schema.sql:/docker-entrypoint-initdb.d/tides.sql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOSTS: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASS}
      UPLOAD_LIMIT: 300M

volumes:
  dbdata: {}